Logical: SnomedClinicalDrug
Title: "SNOMED Clinical Drug"
Description: "SNOMED CT Clinical Drug concept model"

* manufacturedDoseForm 0..1 Code "Attribute |Has manufactured dose form|"
* unitOfPresentation 0..1 Code "Attribute |Has unit of presentation|"
* unitOfPresentationSizeQuantity 0..1 Decimal "Attribute |Unit of presentation size quantity|"
* unitOfPresenationSizeUnit 0..1 Code "Attribute |Unit of presentation size unit|"
* baseActiveIngredientCount 0..1 Integer "Attribute |Count of base of active ingredient|"
* activeIngredientCount 0..1 Integer "Attribute |Count of active ingredient|"
* playsRole 0..1 Code "Therapeutic role of the medicinal product. Attribute |Plays role|"
* ingredient 0..* BackboneElement "Active ingredients and strengths of the manufactured product"
  * preciseActiveIngredient 0..1 Code "Attribute |Has precise active ingredient|"
  * basisOfStrengthSubstance 0..* Code "Attribute |Has basis of strength substance|. Maps to reference strength substance in IDMP."
  * strength 0..1 BackboneElement "Amount of the substance recorded as basis of strength"
    * presentationStrength 0..* BackboneElement "Presentation strength"
      * numeratorValue 0..1 Decimal "Attribute |Has presentation strength numerator value|"
      * numeratorUnit 0..1 Code "Attribute |Has presentation strength numerator unit|"
      * denominatorValue 0..1 Integer "Attribute |Has presentation strength denominator value|"
      * denominatorUnit 0..1 Code "Attribute |Has presentation strength denominator unit|"
    * concentrationStrength 0..1 BackboneElement "Concentration strength"
      * numeratorValue 0..1 Decimal "Attribute |Has concentration strength numerator value|"
      * numeratorUnit 0..1 Code "Attribute |Has concentration strength numerator unit|"
      * denominatorValue 0..1 Integer "Attribute |Has concentration strength denominator value|"
      * denominatorUnit 0..1 Code "Attribute |Has concentration strength denominator unit|"