/*
Logical: SnomedClinicalDrug
Title: "SNOMED Clinical Drug"
Description: "SNOMED CT Clinical Drug concept model"

* manufacturedDoseForm 0..1 CD "Attribute |Has manufactured dose form|"
* unitOfPresentation 0..1 CD "Attribute |Has unit of presentation|"
* unitOfPresentationSizeQuantity 0..1 REAL "Attribute |Unit of presentation size quantity|"
* unitOfPresenationSizeUnit 0..1 CD "Attribute |Unit of presentation size unit|"
* baseActiveIngredientCount 0..1 INT "Attribute |Count of base of active ingredient|"
* activeIngredientCount 0..1 INT "Attribute |Count of active ingredient|"
* playsRole 0..1 CD "Therapeutic role of the medicinal product. Attribute |Plays role|"
* ingredient 0..* Class "Active ingredients and strengths of the manufactured product"
  * preciseActiveIngredient 0..1 CD "Attribute |Has precise active ingredient|"
  * basisOfStrengthSubstance 0..* CD "Attribute |Has basis of strength substance|. Maps to reference strength substance in IDMP."
  * strength 0..1 Class "Amount of the substance recorded as basis of strength"
    * presentationStrength 0..* Class "Presentation strength"
      * numeratorValue 0..1 REAL "Attribute |Has presentation strength numerator value|"
      * numeratorUnit 0..1 CD "Attribute |Has presentation strength numerator unit|"
      * denominatorValue 0..1 INT "Attribute |Has presentation strength denominator value|"
      * denominatorUnit 0..1 CD "Attribute |Has presentation strength denominator unit|"
    * concentrationStrength 0..1 Class "Concentration strength"
      * numeratorValue 0..1 REAL "Attribute |Has concentration strength numerator value|"
      * numeratorUnit 0..1 CD "Attribute |Has concentration strength numerator unit|"
      * denominatorValue 0..1 INT "Attribute |Has concentration strength denominator value|"
      * denominatorUnit 0..1 CD "Attribute |Has concentration strength denominator unit|"
*/

Logical: SnomedFhirClinicalDrug
Title: "SNOMED Clinical Drug FHIR"
Description: "SNOMED CT Clinical Drug concept model with FHIR data types"

* manufacturedDoseForm 0..1 code "Attribute |Has manufactured dose form|"
* unitOfPresentation 0..1 code "Attribute |Has unit of presentation|"
* unitOfPresentationSizeQuantity 0..1 decimal "Attribute |Unit of presentation size quantity|"
* unitOfPresenationSizeUnit 0..1 code "Attribute |Unit of presentation size unit|"
* baseActiveIngredientCount 0..1 integer "Attribute |Count of base of active ingredient|"
* activeIngredientCount 0..1 integer "Attribute |Count of active ingredient|"
* playsRole 0..1 code "Therapeutic role of the medicinal product. Attribute |Plays role|"
* ingredient 0..* BackboneElement "Active ingredients and strengths of the manufactured product"
  * preciseActiveIngredient 0..1 code "Attribute |Has precise active ingredient|"
  * basisOfStrengthSubstance 0..* code "Attribute |Has basis of strength substance|. Maps to reference strength substance in IDMP."
  * strength 0..1 BackboneElement "Amount of the substance recorded as basis of strength"
    * presentationStrength 0..* BackboneElement "Presentation strength"
      * numeratorValue 0..1 decimal "Attribute |Has presentation strength numerator value|"
      * numeratorUnit 0..1 code "Attribute |Has presentation strength numerator unit|"
      * denominatorValue 0..1 integer "Attribute |Has presentation strength denominator value|"
      * denominatorUnit 0..1 code "Attribute |Has presentation strength denominator unit|"
    * concentrationStrength 0..1 BackboneElement "Concentration strength"
      * numeratorValue 0..1 decimal "Attribute |Has concentration strength numerator value|"
      * numeratorUnit 0..1 code "Attribute |Has concentration strength numerator unit|"
      * denominatorValue 0..1 integer "Attribute |Has concentration strength denominator value|"
      * denominatorUnit 0..1 code "Attribute |Has concentration strength denominator unit|"
